"""text size and archieved view

Revision ID: bc4d7bdd0682
Revises: 847f1cbeb8f4
Create Date: 2018-03-18 17:25:13.903523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4d7bdd0682'
down_revision = '847f1cbeb8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'archived')
    # ### end Alembic commands ###
